# Customizing static analysis
# https://dart.dev/guides/language/analysis-options/
# https://dart-lang.github.io/linter/lints/

#nclude: package:effective_dart/lib/analysis_options.yaml

analyzer:
  exclude:
    # Web
    - 'web/**'
    # Build
    - 'build/**'
    # Generated code
    - 'lib/**.g.dart'
    - 'lib/**.freezed.dart'
    - 'lib/**.graphql.dart'
    - 'lib/**.gr.dart'
    - 'lib/generated_plugin_registrant.dart'
    - '.test_coverage.dart'
    - 'lib/pigeon.dart'
    # Assets
    - 'assets/**'

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    # Info
    todo: info
    directives_ordering: info
    always_declare_return_types: info

    # Warning
    unsafe_html: warning
    no_logic_in_create_state: warning
    empty_catches: warning

    # Error
    always_use_package_imports: error
    avoid_relative_lib_imports: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    cancel_subscriptions: error
    close_sinks: error
    valid_regexps: error
    always_require_non_null_named_parameters: error

linter:
  rules:
    # Disabled
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    avoid_web_libraries_in_flutter: false
    prefer_relative_imports: false
    # Enabled
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    no_logic_in_create_state: true
    unsafe_html: true
    empty_catches: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    valid_regexps: true
    always_require_non_null_named_parameters: true